openapi: 3.0.3
info:
  title: Tutorial & Comment Management API
  description: API pour la gestion des tutoriels et commentaires avec Spring Boot WebFlux
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:8080
    description: Serveur de développement
  - url: https://api.example.com
    description: Serveur de production

paths:
  /api/tutorials:
    get:
      tags:
        - Tutorials
      summary: Récupérer tous les tutoriels
      description: Retourne la liste de tous les tutoriels, avec possibilité de filtrer par titre
      operationId: getAllTutorials
      parameters:
        - name: title
          in: query
          description: Filtre optionnel par titre (recherche partielle)
          required: false
          schema:
            type: string
            example: "Spring Boot"
      responses:
        '200':
          description: Liste des tutoriels récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tutorial'
        '500':
          description: Erreur serveur interne
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags:
        - Tutorials
      summary: Créer un nouveau tutoriel
      description: Crée un nouveau tutoriel avec les informations fournies
      operationId: createTutorial
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TutorialRequest'
      responses:
        '201':
          description: Tutoriel créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tutorial'
        '400':
          description: Données invalides
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erreur serveur interne
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/tutorials/all:
    get:
      tags:
        - Tutorials
      summary: Récupérer tous les tutoriels (endpoint alternatif)
      description: Retourne la liste complète de tous les tutoriels sans filtrage
      operationId: getAllTutorialsAlternative
      responses:
        '200':
          description: Liste des tutoriels récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tutorial'
        '500':
          description: Erreur serveur interne
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/tutorials/{id}:
    get:
      tags:
        - Tutorials
      summary: Récupérer un tutoriel par ID
      description: Retourne les détails d'un tutoriel spécifique
      operationId: getTutorialById
      parameters:
        - name: id
          in: path
          description: Identifiant unique du tutoriel
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: Tutoriel trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tutorial'
        '404':
          description: Tutoriel non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erreur serveur interne
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/tutorials/{tutorialId}/comments:
    get:
      tags:
        - Comments
      summary: Récupérer tous les commentaires d'un tutoriel
      description: Retourne la liste des commentaires associés à un tutoriel spécifique
      operationId: getAllCommentsByTutorialId
      parameters:
        - name: tutorialId
          in: path
          description: Identifiant du tutoriel
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: Liste des commentaires récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
        '404':
          description: Tutoriel non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erreur serveur interne
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags:
        - Comments
      summary: Créer un commentaire pour un tutoriel
      description: Ajoute un nouveau commentaire à un tutoriel spécifique
      operationId: createComment
      parameters:
        - name: tutorialId
          in: path
          description: Identifiant du tutoriel
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentRequest'
      responses:
        '201':
          description: Commentaire créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '400':
          description: Données invalides
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Tutoriel non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erreur serveur interne
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/comments/{id}:
    get:
      tags:
        - Comments
      summary: Récupérer un commentaire par ID
      description: Retourne les détails d'un commentaire spécifique
      operationId: getCommentsById
      parameters:
        - name: id
          in: path
          description: Identifiant unique du commentaire
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: Commentaire trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '404':
          description: Commentaire non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erreur serveur interne
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Tutorial:
      type: object
      required:
        - id
        - title
        - description
        - published
      properties:
        id:
          type: integer
          format: int64
          description: Identifiant unique du tutoriel
          example: 1
        title:
          type: string
          description: Titre du tutoriel
          example: "Introduction à Spring Boot"
          maxLength: 255
        description:
          type: string
          description: Description détaillée du tutoriel
          example: "Ce tutoriel présente les concepts de base de Spring Boot"
          maxLength: 1000
        published:
          type: boolean
          description: Statut de publication du tutoriel
          example: true
        createdAt:
          type: string
          format: date-time
          description: Date de création du tutoriel
          example: "2024-01-15T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Date de dernière modification
          example: "2024-01-15T10:30:00Z"

    TutorialRequest:
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
          description: Titre du tutoriel
          example: "Introduction à Spring Boot"
          maxLength: 255
          minLength: 1
        description:
          type: string
          description: Description détaillée du tutoriel
          example: "Ce tutoriel présente les concepts de base de Spring Boot"
          maxLength: 1000
          minLength: 1

    Comment:
      type: object
      required:
        - id
        - content
        - tutorialId
      properties:
        id:
          type: integer
          format: int64
          description: Identifiant unique du commentaire
          example: 1
        content:
          type: string
          description: Contenu du commentaire
          example: "Excellent tutoriel, très bien expliqué !"
          maxLength: 2000
        author:
          type: string
          description: Nom de l'auteur du commentaire
          example: "Jean Dupont"
          maxLength: 100
        tutorialId:
          type: integer
          format: int64
          description: Identifiant du tutoriel associé
          example: 1
        createdAt:
          type: string
          format: date-time
          description: Date de création du commentaire
          example: "2024-01-15T14:30:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Date de dernière modification
          example: "2024-01-15T14:30:00Z"

    CommentRequest:
      type: object
      required:
        - content
      properties:
        content:
          type: string
          description: Contenu du commentaire
          example: "Excellent tutoriel, très bien expliqué !"
          maxLength: 2000
          minLength: 1
        author:
          type: string
          description: Nom de l'auteur du commentaire
          example: "Jean Dupont"
          maxLength: 100

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: Code d'erreur HTTP
          example: 404
        message:
          type: string
          description: Message d'erreur descriptif
          example: "Ressource non trouvée"
        details:
          type: string
          description: Détails supplémentaires sur l'erreur
          example: "Le tutoriel avec l'ID 123 n'existe pas"
        timestamp:
          type: string
          format: date-time
          description: Horodatage de l'erreur
          example: "2024-01-15T10:30:00Z"

  responses:
    NotFound:
      description: Ressource non trouvée
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    BadRequest:
      description: Requête invalide
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    InternalServerError:
      description: Erreur serveur interne
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

tags:
  - name: Tutorials
    description: Opérations liées à la gestion des tutoriels
  - name: Comments
    description: Opérations liées à la gestion des commentaires